# Welcome to Jekyll!
#

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
#- jekyll-paginate

# 3. Gem settings
#paginate: 2 # jekyll-paginate > items per page
#paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: BrianPSchmidt # jekyll-seo-tag > Owners twitter username
author: Brian{Schmidt # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: BrianSchmidt # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/BrianPSchmidt
    - https://www.linkedin.com/in/brian-schmidt-2a606263/
    - https://github.com/bps10

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: false
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "/static/img/S20076R_montage_6_cropped_landscape.png"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/static/img/S20076R_montage_6_cropped_landscape.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right

lang: en-GB # Set the site language
title: "Brian P. Schmidt" # Site name or title, also used in jekyll-seo-tag

logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag

description: "Unraveling visual perception, one cell at a time" # Site description and default description, also used in jekyll-seo-tag

url: "https://bps10.github.io" # Site url, also used in jekyll-seo-tag
baseurl: "/"
repo: "https://github.com/bps10/bps10.github.io"
email: "brian.patrick.schmidt@gmail.com"


# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account

#avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c"
# Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

google_analytics: 'UA-38977206-1'

# service_worker: false # Will turn off the service worker if set to false

css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  Research: /research/
  #Blog: /blog/
  #Categories: /categories/
  #Search: /search/
  #Fork Me: https://github.com/bps10/bps10.github.io

navigation_footer:
  Created by Brian Schmidt: https://bps10.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/BrianPSchmidt
  LinkedIn: https://www.linkedin.com/in/brian-schmidt-2a606263/
  GitHub: https://github.com/bps10
  #RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  # Twitter: "#0d94e7"
  # facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
  